
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'rightIDIFFORPRINTrightIGUALrightIGUALIGUALleftMAYORMENORleftSUMARESTAleftMULTIDIVleftPARIZQUIERDOPARDERECHOleftLLIZQUIERDALLDERECHACOMMA DIV EJECUTABLE FOR FUNCTION ID IF IGUAL IGUALIGUAL LLDERECHA LLIZQUIERDA MAYOR MAYORIGUAL MENOR MENORIGUAL MULTI NUMBER PARDERECHO PARIZQUIERDO PRINT PYC RESTA RETURN STRING SUMA VARf : FUNCTION fmfm : EJECUTABLE PARIZQUIERDO PARDERECHO bcbc : LLIZQUIERDA comp\n    comp : if LLDERECHA\n          | for LLDERECHA\n          | print LLDERECHA\n          | asg LLDERECHA\n    if : IF PARIZQUIERDO eif PARDERECHO PYC compifeif : ID o NUMBER\n    compif : if\n            | for\n            | print \n            | asg\n            | empty\n     \n    o : MENOR\n       | MAYOR\n       | MAYORIGUAL\n       | MENORIGUAL\n       | IGUALIGUAL \n    \n    for : FOR PARIZQUIERDO efor PARDERECHO PYC compifefor : ID op NUMBER op : MENOR print : PRINT PARIZQUIERDO comprint PARDERECHO PYC compif\n    comprint : STRING con\n              | ID\n    con : SUMA ID\n            | empty\n    asg : VAR ID compasg PYC compif\n    compasg : IGUAL valor \n             | empty \n    \n    valor : ID\n           | NUMBER   \n    empty :'
    
_lr_action_items = {'FUNCTION':([0,],[2,]),'$end':([1,3,7,9,18,19,20,21,],[0,-1,-2,-3,-4,-5,-6,-7,]),'EJECUTABLE':([2,],[4,]),'PARIZQUIERDO':([4,14,15,16,],[5,22,23,24,]),'PARDERECHO':([5,26,28,30,31,32,47,49,55,57,59,],[6,36,43,46,-33,-25,-24,-27,-9,-21,-26,]),'LLIZQUIERDA':([6,],[8,]),'IF':([8,50,54,56,58,],[14,14,14,14,14,]),'FOR':([8,50,54,56,58,],[15,15,15,15,15,]),'PRINT':([8,50,54,56,58,],[16,16,16,16,16,]),'VAR':([8,50,54,56,58,],[17,17,17,17,17,]),'LLDERECHA':([10,11,12,13,50,54,56,58,60,61,62,63,64,65,66,67,68,],[18,19,20,21,-33,-33,-33,-33,-28,-10,-11,-12,-13,-14,-8,-20,-23,]),'ID':([17,22,23,24,34,48,],[25,27,29,32,52,59,]),'STRING':([24,],[31,]),'IGUAL':([25,],[34,]),'PYC':([25,33,35,36,43,46,51,52,53,],[-33,50,-30,54,56,58,-29,-31,-32,]),'MENOR':([27,29,],[38,45,]),'MAYOR':([27,],[39,]),'MAYORIGUAL':([27,],[40,]),'MENORIGUAL':([27,],[41,]),'IGUALIGUAL':([27,],[42,]),'SUMA':([31,],[48,]),'NUMBER':([34,37,38,39,40,41,42,44,45,],[53,55,-15,-16,-17,-18,-19,57,-22,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'f':([0,],[1,]),'fm':([2,],[3,]),'bc':([6,],[7,]),'comp':([8,],[9,]),'if':([8,50,54,56,58,],[10,61,61,61,61,]),'for':([8,50,54,56,58,],[11,62,62,62,62,]),'print':([8,50,54,56,58,],[12,63,63,63,63,]),'asg':([8,50,54,56,58,],[13,64,64,64,64,]),'eif':([22,],[26,]),'efor':([23,],[28,]),'comprint':([24,],[30,]),'compasg':([25,],[33,]),'empty':([25,31,50,54,56,58,],[35,49,65,65,65,65,]),'o':([27,],[37,]),'op':([29,],[44,]),'con':([31,],[47,]),'valor':([34,],[51,]),'compif':([50,54,56,58,],[60,66,67,68,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> f","S'",1,None,None,None),
  ('f -> FUNCTION fm','f',2,'p_f','Sintaxis.py',26),
  ('fm -> EJECUTABLE PARIZQUIERDO PARDERECHO bc','fm',4,'p_fm','Sintaxis.py',31),
  ('bc -> LLIZQUIERDA comp','bc',2,'p_bc','Sintaxis.py',35),
  ('comp -> if LLDERECHA','comp',2,'p_comp','Sintaxis.py',39),
  ('comp -> for LLDERECHA','comp',2,'p_comp','Sintaxis.py',40),
  ('comp -> print LLDERECHA','comp',2,'p_comp','Sintaxis.py',41),
  ('comp -> asg LLDERECHA','comp',2,'p_comp','Sintaxis.py',42),
  ('if -> IF PARIZQUIERDO eif PARDERECHO PYC compif','if',6,'p_if','Sintaxis.py',47),
  ('eif -> ID o NUMBER','eif',3,'p_eif','Sintaxis.py',51),
  ('compif -> if','compif',1,'p_compif','Sintaxis.py',56),
  ('compif -> for','compif',1,'p_compif','Sintaxis.py',57),
  ('compif -> print','compif',1,'p_compif','Sintaxis.py',58),
  ('compif -> asg','compif',1,'p_compif','Sintaxis.py',59),
  ('compif -> empty','compif',1,'p_compif','Sintaxis.py',60),
  ('o -> MENOR','o',1,'p_o','Sintaxis.py',66),
  ('o -> MAYOR','o',1,'p_o','Sintaxis.py',67),
  ('o -> MAYORIGUAL','o',1,'p_o','Sintaxis.py',68),
  ('o -> MENORIGUAL','o',1,'p_o','Sintaxis.py',69),
  ('o -> IGUALIGUAL','o',1,'p_o','Sintaxis.py',70),
  ('for -> FOR PARIZQUIERDO efor PARDERECHO PYC compif','for',6,'p_for','Sintaxis.py',76),
  ('efor -> ID op NUMBER','efor',3,'p_efor','Sintaxis.py',80),
  ('op -> MENOR','op',1,'p_op','Sintaxis.py',84),
  ('print -> PRINT PARIZQUIERDO comprint PARDERECHO PYC compif','print',6,'p_print','Sintaxis.py',88),
  ('comprint -> STRING con','comprint',2,'p_comprint','Sintaxis.py',93),
  ('comprint -> ID','comprint',1,'p_comprint','Sintaxis.py',94),
  ('con -> SUMA ID','con',2,'p_con','Sintaxis.py',99),
  ('con -> empty','con',1,'p_con','Sintaxis.py',100),
  ('asg -> VAR ID compasg PYC compif','asg',5,'p_asg','Sintaxis.py',105),
  ('compasg -> IGUAL valor','compasg',2,'p_compasg','Sintaxis.py',110),
  ('compasg -> empty','compasg',1,'p_compasg','Sintaxis.py',111),
  ('valor -> ID','valor',1,'p_valor','Sintaxis.py',117),
  ('valor -> NUMBER','valor',1,'p_valor','Sintaxis.py',118),
  ('empty -> <empty>','empty',0,'p_empty','Sintaxis.py',123),
]
